[test_config]
name = "courier"
manifest-path = "./Cargo.toml"
run-ignored = false
ignore-panics = false
force-clean = false
skip-clean = true
verbose = false 
debug = false
dump-traces = false
count = true
line-coverage = false
branch-coverage = true
output-dir = "./coverage_output"
forward-signals = false
no-dead-code = false
all-features = false
no-default-features = false
workspace = false
test-timeout = "10m"
release = false
no-run = false
locked = false
frozen = false
target-dir = "./target"
offline = false
command = "Test"
run-types = ["AllTargets"]
packages = []
exclude = []
exclude-files = ["tests/data/*"]
include-files = []
args = []
unstable-features = []
generate = []
test-names = []
bin-names = []
example-names = []
bench-names = []
no-fail-fast = false
avoid-cfg-tarpaulin = false
color = "Auto"
follow-exec = true
implicit-test-threads = true
engine = "Llvm"
include-tests = true
objects = []
profraw-folder = "./target/profraw"
fail-immediately = false
stderr = false