use clap::{Args, ValueEnum};

#[derive(Args)]
pub struct StartArgs {
  #[arg(long, short = 'b')]
  bootloader: BootloaderList,
}

// Enum + execute, auto-generated by build/build_tool.py
include!("generated/bootloader.rs");
