[package]
name = "event"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }

[dependencies]
crossbeam-channel.workspace = true
thiserror.workspace = true
dashmap = "6.2.1"
